services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_started
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/music-streaming
      - JWT_SECRET=${JWT_SECRET}
      - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
